name: Build Android APK with Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Cloud Repository
      uses: actions/checkout@v4

    - name: Get Buildozer Cache
      uses: actions/cache@v4
      with:
        path: ./.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}

    # THIS STEP AUTO-ACCEPTS THE ANDROID LICENSES
    - name: Accept Android SDK Licenses
      run: |
        mkdir -p mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses || true

    - name: Build with Buildozer Action
      uses: ArtemGovorov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: master

    - name: Upload Finished APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AceCalculator-APK
        path: ${{ steps.buildozer.outputs.filename }}
